language: java

jdk:
  - oraclejdk8

sudo: required

script:
  - sudo apt-get update && sudo apt-get install oracle-java8-installer
  - java -version

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
