language: java
jdk:
- oraclejdk8
sudo: true
services:
- redis-server
before_cache:
- rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
cache:
  directories:
  - "$HOME/.gradle/caches/"
  - "$HOME/.gradle/wrapper/"
deploy:
  provider: heroku
  app:
    dev: secure-inlet-7452
    Spark: powerful-savannah-2609
    master: snidgengid
  api_key:
    secure: K+BcySA1cThs4pmTdamWf4Yof66a9jZaNsN2tM9wLzLUq0nT6UY/qUgfQ5RpN5cXFPvFp1s+vEPRVQa267jWz+1tM9L4ZbSF/oPvnMg89eML7dnWECshk0NxqYe70eTok25+RSwwtZ0428IB6tw0u/AFUNEQUOYJbCV5IEeO2KWT6MaAW6ywIIp6Rm6U0AGyluGJc3p6+oiwLEzBzgxIT7oGp8bwa73sFMiYnSh0zzwm45qPKeqPjQy1OtA/4buWDx2ChPdk3SDkzF6PYq6CZVImuQLZ3P/i+hXp2I8KPlIfwD6YhxS1Y3F91b28RPgpxp+VTl0Q6mU2bmkqRX8ZJBKVqyBXZmu5lHWRcx95mUg6lXEywJoDiSktWyN0CSoZj4jS8s6ZANsv+wnwwpV6FpeURgldx3yjgTY0CstFPrUDTF3UFXovguI/XLludxJoNzBtppjWE9cJ060V164ohyLa0OqPVcSE/u7+7GnDNka691BgfO9IUWpmHkrZqJ3XeRey9E5e22dH3V6YsQe7sv2NmeXeuqAhd0SBioMLcWAnzsr+0E3mTmoP0lX9gPZ6YzOiG8sJAg/24pi8xxq/+ttVfLRlQnuIaVqQx6OnmBWDeAtVbvK07dvoXHPqmVCoHsUobR5NRZuNqXvtLXvGJEtmvJJappOENjikTx02pwY=
before_install:
- sudo pip install codecov
after_success:
- codecov
notifications:
  webhooks:
    urls:
    - https://webhooks.gitter.im/e/2c67b3ae594491e55883
    on_success: always
    on_failure: always
    on_start: always
addons:
  sauce_connect:
    username: soring
    access_key:
      secure: lPZ5ipFj59nm9ei7656mdi5TMx8LYjZ53jGosJAGwchVy+Ks7PvuLntS9tkqBAUJ0D6spuhHVz2Cce64pCR6kvEM7WYtgI+HSrd0JBU+nD8hrF2vG4KaWdyM8pCcgYAus2oOtwksI249ZJu+vV5a8xfoyH9T6bDhbtb3lYSkAd38qa1mmcfdp3Y3mfYw9OrsZlgRMNyTupnyivn+fWV7iyu+uzjT+vAYmwOjMUtBBnFWTK7WHeYCdjUgkvUuPgZHd+yTJG4UoIL4yGUH8fa83SGzAVnHihlOuTySd7aTwwNOre/KwgGJr7EYsHeipduv+YgTXy/kl7BIf1K9tkfxJstxrvBQZB/s+By5QO0g7e5DlKO0KRldc4vMndRVbx1HXS690t1ayga0YuMhKLbPQvhlIqH/EvSY5/UqBnG3KGFMTNQwZDizzez3ns+6BRZWv+qoXRo5vFbTwdrC4vfFbsk1aDJldg4bbH9NhshP+xIRcssuUVJ9bcJyAYDO3MbOblEx8/6pGbWt2mqQ9MgLkz8QIdWjxe3pWGrtWhRsDcx66W6DsvE+x9gEtWcSWq3HXFjTyNPrbDqyKO1fSeX2VBDCk8uyp+hTl7RdgfjJU6NpbI7LWMZYsL9QCaTlQJfwQ8DV0n9gn68+7EPz4uFs4XQGQpFAvdoDgmjgcRqYgXs=
script:
- java -cp ./build/libs/tictactoe.jar is.ru.snidgengid.tictactoe.Web
